USE Torverbarber;
INSERT INTO Servizio (nome, descrizione, prezzo, durataMinuti) VALUES
('Taglio Classico', 'Taglio di capelli tradizionale con forbici e macchinetta.', 20.00, 30),
('Taglio e Shampoo', 'Taglio di capelli seguito da lavaggio con shampoo di qualità.', 25.00, 40),
('Taglio con sfumatura', 'Taglio sfumato perfetto per un look moderno e definito.', 22.00, 35),
('Taglio bambino', 'Taglio di capelli per bambini fino a 12 anni.', 15.00, 25),
('Rasatura Classica', 'Rasatura tradizionale con panno caldo e rasoio a mano libera.', 18.00, 30),
('Rasatura Barba e Modellatura', 'Rifinitura e definizione della barba con rasoio e forbici.', 22.00, 35),
('Barba e Shampoo', 'Lavaggio e cura della barba con oli e prodotti specifici.', 20.00, 30),
('Rasatura con Panno Caldo', 'Rasatura profonda con trattamento di panno caldo per la pelle.', 25.00, 40),
('Modellatura Barba', 'Sagomatura della barba con forbici e trimmer per un look ordinato.', 18.00, 25),
('Taglio Completo + Barba', 'Taglio capelli e modellatura barba con styling finale.', 35.00, 50),
('Ritocco Capelli e Barba', 'Ritocco veloce per capelli e barba per mantenere il look.', 15.00, 20),
('Trattamento Barba Nutriente', 'Trattamento con oli e balsami per idratare e nutrire la barba.', 20.00, 30),
('Rasatura con Lama e Olio', 'Rasatura profonda con olio pre-barba e lama professionale.', 25.00, 35),
('Rasatura Old School', 'Rasatura con pennello, sapone e rasoio a mano libera.', 28.00, 45),
('Permanente per Capelli', 'Trattamento per creare ricci o onde definite nei capelli.', 50.00, 60),
('Trattamento Antiforfora', 'Shampoo e massaggio al cuoio capelluto con prodotti specifici.', 20.00, 30),
('Trattamento Anticaduta', 'Massaggio e applicazione di lozioni anticaduta per capelli.', 25.00, 30),
('Colorazione Capelli', 'Tinta per capelli con prodotti di qualità.', 35.00, 50),
('Colpi di Sole', 'Schiariture leggere per un effetto naturale e luminoso.', 45.00, 60),
('Decolorazione', 'Schiaritura intensa per ottenere un biondo platino.', 55.00, 75),
('Massaggio al Cuoio Capelluto', 'Massaggio rilassante per stimolare la circolazione e ridurre lo stress.', 20.00, 25),
('Trattamento Viso Uomo', 'Pulizia profonda del viso con maschera purificante.', 30.00, 40);