USE Torverbarber;
INSERT INTO Zona (nome, descrizione, ResponsabileID) VALUES ("Oricola", "Economico mentre recare dolore muovere discutere soldato quindi qualcuno ponte sotto segno.", NULL),
("Bannio Anzino", "Procedere presso vino ecco preoccupare epoca dove chiaro pietà.", NULL),
("San Germano", "Semplice ritrovare famoso dove distinguere impossibile passione profondo azione.", NULL),
("Barbarano Vicentino", "Collo classe limitare prova chiudere male autore azzurro rivedere frase oggetto gioco.", NULL),
("Brissogne", "Esso fuori sperare destro posare legare estremo inizio lotta facile ridurre rientrare.", NULL),
("Ischia Trentina", "Latte finire offrire vero animo apparire esporre.", NULL),
("Lisiera", "Primo giovane pesare come facile morte limitare.", NULL),
("Cesarolo", "Luce contrario servire esame alzare capello luogo albergo sacro attività.", NULL),
("Pietrasecca", "Differenza paura pazzo crisi treno mamma il spingere favore elemento estendere guardare speranza.", NULL),
("Minervino Di Lecce", "Unire accompagnare matrimonio tardi campo necessità.", NULL),
("Fenile", "Buttare capitare volta stare personaggio titolo fine sala osservare.", NULL),
("Barbania", "Appunto medio distanza automobile anche vestire proposta coscienza capace economico.", NULL),
("Dazio", "Giorno moglie capo guardare eccellenza condurre famoso.", NULL),
("Le Crete", "Domanda sognare perfino rompere centrale sorridere casa.", NULL),
("Saviore Dell'Adamello", "Peggio cui ascoltare campo ricco sopra palazzo anzi signore imparare piccolo.", NULL),
("Pian Del Lago", "Soltanto dire altro io cittadino scala fatto.", NULL),
("Unterplanitzing", "Differenza spalla dolce giallo pena fermo causa lingua permettere osservare lontano bambino arrivare.", NULL),
("Vecchiano", "Fissare sociale riempire prevedere figurare restare strano soldato volare.", NULL),
("San Martino In Badia", "Intenzione moderno guidare accordo diretto vendere spirito aggiungere oggetto solo famoso se volto.", NULL),
("Maranzana", "Guidare sapere scena vuoto fede pianura scuola peso.", NULL);