USE Torverbarber;
INSERT INTO Zona (nome, descrizione, ResponsabileID) VALUES ("Mollaro", "Gridare vasto occasione scuola principe piangere appoggiare società errore superiore confessare età avvertire spesso.", NULL),
("Gattinara", "Offrire loro mare tutto unire chiedere invitare anzi.", NULL),
("Piatto", "Prova politico rappresentare base primo limite motivo luce servizio fretta faccia.", NULL),
("Crava", "Tale zona ridurre noto punta venire.", NULL),
("Cesenatico", "Scappare vestito molto affare verità pure campo discorso attraversare questo forza senso bere.", NULL),
("Strettura", "Chilometro voce meglio li in aria immagine scegliere istante credere.", NULL),
("Fraore", "Operazione materia sperare servire rifiutare bambino.", NULL),
("Semproniano", "Appartenere diritto uno signore completamente caratteristico sede passione gusto rivolgere movimento.", NULL),
("Monteduro", "Dietro tornare particolare viso riferire patria linea opporre tratto proposta volere tu.", NULL),
("Bulgarograsso", "Fiume procedere rapporto mare assistere alcuno.", NULL),
("Vilminore Di Scalve", "Circa mattino magari nulla provocare medesimo su libertà senso gesto differenza adesso rivelare.", NULL),
("Partino", "Comprendere risultato fuori privato fantasia quale.", NULL),
("Dorsoduro", "Riprendere noi ripetere assistere papà momento buono.", NULL),
("Balsorano Nuovo", "Calcio tavola volta intero lago stringere grazia campagna risposta collina.", NULL),
("Granozzo", "Presidente notte riempire provincia giovane rapido faccia limite.", NULL),
("Villar", "Folla festa avanzare capace ricordare giungere centrale sorella prova poesia bastare.", NULL),
("Cis", "Circa giardino effetto rivedere bene durare capo quanto arma pubblicare alzare fissare partire.", NULL),
("Verza", "Secolo mi superiore primo patria base.", NULL),
("Vicomero", "Giudizio arrivare qualunque certo finestra scrittore luogo volto decidere attorno momento cittadino presidente.", NULL),
("Torriglia", "Celebrare scrivere necessario veramente mese parete tra partire aumentare minore stupido indietro preferire.", NULL);